language: c
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-docker.sh
script: bash -ex .travis-docker.sh
services:
- docker
env:
  global:
  - PINS="olinq:."
  - DISTRO="ubuntu-16.04"
  - PACKAGE="olinq"
  matrix:
  - OCAML_VERSION="4.03"
  - OCAML_VERSION="4.09"
  - OCAML_VERSION="4.10"
